### ISSUE TITLE
How to resize the car image?

### ISSUE THREAD

**Issue by VitaliFrolov** [David-Development/lovelace-carnet-card#1]
Hello,

Thank you for a great card!

I there a way to resize the car? The card id huge.

**Comment by David-Development** [comment]
Hi @VitaliFrolov! Sorry for the delay. Currently there is no way to resize the card. I'll have a look at it!

**Comment by David-Development** [comment]
Just added two additional attributes to scale the card down. Feel free to check them out!

```
scale: 0.5 # optional (if you want the card to be smaller)
height: 270px # optional (if you want the card to be smaller)
```
